### ISSUE TITLE
Don't think linux has tar --disable-copyfile

### ISSUE THREAD

**Issue by Goddard** [amitds1997/remote-nvim.nvim#100]
Just trying out your plugin and ran into this error.  

"tar: unrecognized option '--disable-copyfile'"

I'm on Linux and not sure if this is BSD specific, but currently makes using compression to copy things unusable.

Removed the reference in this file [lua/remote-nvim/providers/ssh/ssh_executor.lua](https://github.com/amitds1997/remote-nvim.nvim/blob/0bebd36c6699b9dc7649ee8246a4b6dd3c7a4e52/lua/remote-nvim/providers/ssh/ssh_executor.lua#L63)

Now it works.

**Comment by amitds1997** [comment]
Thanks! I would push a fix for this. I mostly tested this from MacOS so this must have crept in. I'll do a quick fix.
