### ISSUE TITLE
Add support for Passphrases on protected private keys. 

### ISSUE THREAD

**Issue by edgerunnergit** [amitds1997/remote-nvim.nvim#103]
**Is your feature request related to a problem? Please describe.**
Yes. Right now whenever I try to ssh into any host using a protected private key from my local machine, remote-nvim.nvim doesn't let me input the passphrase.

**Describe the solution you'd like**
I would love if it let me enter the passphrase like it let's me enter the normal password. 

**Screenshots:**
![image](https://github.com/amitds1997/remote-nvim.nvim/assets/111838417/580177b9-e4d5-446d-9dff-1d5cc8ab1790)

**Comment by amitds1997** [comment]
With the latest commit, you should be able to do this now. Let me know if you still face any issues.
