### ISSUE TITLE
Resize RemoteNvim Window

### ISSUE THREAD

**Issue by ihersom** [amitds1997/remote-nvim.nvim#107]
When resizing a terminal window, primarily when making it larger, the inner remote nvim session does not seem to resize with the terminal and stays the same size when connected.

I would like to see the remote nvim resize with the terminal either automatically, or by issuing a : command.

**Comment by amitds1997** [comment]
Thanks for reporting this. Should be fixed (by https://github.com/amitds1997/remote-nvim.nvim/pull/108) and present in the latest release ([v0.2.7](https://github.com/amitds1997/remote-nvim.nvim/releases/tag/v0.2.7)). The `autocmd` for resize event was not setup.

**Comment by ihersom** [comment]
Awesome, thanks much! Just want to say, this is a great plugin, thanks for all your work on it!
