### ISSUE TITLE
Feature request: Ignore .git folder when copying nvim config to remote host

### ISSUE THREAD

**Issue by tnthi115** [amitds1997/remote-nvim.nvim#141]
## Description

Many of us use git to manage our nvim configs, and copying the `.git` directory over to the remote host seems in most, if not all, cases unnecessary and slow. It might be a good idea to avoid copying it altogether.

**Comment by amitds1997** [comment]
Hi, thanks for reporting this. This is currently not supported by default. Here's how you can do it (This leverages `tar`'s inbuilt VCS feature to exclude any VCS directories):

```lua
require("remote-nvim").setup({
  remote = {
    copy_dirs = {
      config = {
        compression = {
          enabled = true,
          additional_opts = { "--exclude-vcs" },
        },
      },
    },
  },
})
```
This can be repeated for any of the other `nvim` directories as well.

**Comment by tnthi115** [comment]
@amitds1997 Perfect, thank you!
