### ISSUE TITLE
Support explicitly specifying nvim version

### ISSUE THREAD

**Issue by SuperXia123** [amitds1997/remote-nvim.nvim#153]
Some remote machines have only old version GLIBC, which doesn't support nvim-0.10.0. I got the following error when deploying to a remote machine which has GLIBC version 0f 2.17.
```
Searching for free port on the remote machine
    Command: /home/users/yufeng.xia/.remote-nvim/nvim-downloads/v0.10.0/bin/nvim -l /home/users/yufeng.xia/.remote-nvim/scripts/free_port_finder.lua

    /home/users/yufeng.xia/.remote-nvim/nvim-downloads/v0.10.0/bin/nvim: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/users/yufeng.xia/.remote-nvim/nvim-downloads/v0.10.0/bin/nvim)
    /home/users/yufeng.xia/.remote-nvim/nvim-downloads/v0.10.0/bin/nvim: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/users/yufeng.xia/.remote-nvim/nvim-downloads/v0.10.0/bin/nvim)
```

Would it be possible to specify the to-be-installed nvim version on remote machine in the pop-up session? Thanks~

**Comment by amitds1997** [comment]
This should already be possible and you should be able to choose any Neovim version >= 0.9.1. What version are you trying to install?

**Comment by SuperXia123** [comment]
Thanks~ I am trying to install nvim-0.9.5，but I haven't found a place to choose the version.

**Comment by amitds1997** [comment]
It should pop-up automatically (unless you have a saved configuration for that host where you have already selected a version). See the video at timestamp `00:15` under "How to connect to saved host using SSH config file" in the [Demos](https://github.com/amitds1997/remote-nvim.nvim?tab=readme-ov-file#-demos) section.

**Comment by lixiaochuan2020** [comment]
Hi! I initially specified the remote version as 0.10.0, but I found that the GLIBC on the server is not 2.29 but 2.28, so I need to downgrade the version of neovim right? However, every time I reconfigure it, it seems to default to 0.10.0, and there is no pop-up page to guide me to reset. Is this stored in some configuration files?

**Comment by amitds1997** [comment]
Yes, it is. You can follow this comment: https://github.com/amitds1997/remote-nvim.nvim/discussions/122#discussioncomment-9358829 to access the file. You can also just delete the configuration using `RemoteConfigDel` and just re-configure using `RemoteStart`

**Comment by lixiaochuan2020** [comment]
Got it! Thank you.
