### ISSUE TITLE
How to implement local complete installation？

### ISSUE THREAD

**Issue by qlibp** [amitds1997/remote-nvim.nvim#45]
If you show me the path, then I would like to implement such feature! This is the most hardest part for me.

Just like telescope, we have no way to just copy ripgrep from host to remote client as it might not work as a binary… Unless we prepare all the necessary binary for all OS.

Don’t know if python wheel/ nodejs npm stuff can help this out?

**Comment by amitds1997** [comment]
Python or node might not be available on all systems. Specially, docker containers which I plan to support soon. So, there is unfortunately no universal way to install it unless the binary that we need provides for it.

Due to this very issue, the plugin support the `neovim_install_script_path` config key where you can specify your own installation script. You can extend the [packaged installation script](https://github.com/amitds1997/remote-nvim.nvim/blob/82be7fe67ff0896b99b5a19da544554a905a274c/scripts/neovim_install.sh) to install any necessary packages after Neovim gets installed but you would have to do the heavy lifting of installing the correct binary on the correct OS.

One possible way (I have not explored this yet) could be using Homebrew since it is supported on MacOS, Linux and WSL 2. So, you could just use a common syntax to install ripgrep across all systems.

Let me know if you have any suggestions on how we can better support this though. I am open to ideas.

**Comment by amitds1997** [comment]
I gave this some more thought and `3` seems to be the ideal solution for this use case. We would have to do the following to achieve this:

1. In the plugin configuration, add an extra option `remote_tool_list` (this can be named better). It would take a list of tools that need to be installed from [this list](https://webinstall.dev/).
2. Pass this list to the [install script](https://github.com/amitds1997/remote-nvim.nvim/blob/82be7fe67ff0896b99b5a19da544554a905a274c/scripts/neovim_install.sh).
3. For each tool in the list, check if the binary for the tool is present, if not, install it using [webinstall](https://github.com/webinstall/webi-installers).

**Comment by qlibp** [comment]
I have a situation that I can’t access internet on remote machine(e.g. deploying software on a robot and can only access it through local networks), but my laptop/local machine could access internet. Then what’s best workflow for remote-nvim?

**Comment by qlibp** [comment]
From webinstall, I notice there’s a c/cpp complier called zig. If that’s cross-platform,then we may be able to rely on it build binary locally? This the last method  for those package that have no official binary, and the user could still easily port their package to different OS? But this methods require the user to write their own build script.

**Comment by qlibp** [comment]
The list of webinstall is kind of limited. Binary like lazygit/tig/fzf stuff is not presented in the list

**Comment by amitds1997** [comment]
> I have a situation that I can’t access internet on remote machine(e.g. deploying software on a robot and can only access it through local networks), but my laptop/local machine could access internet. Then what’s best workflow for remote-nvim?

Ah! I completely misunderstood the requirement. I thought it was just how to install correct tool binaries for dependencies like `ripgrep`, `gcc`, etc. locally and then copy it over to remote server.

> The list of webinstall is kind of limited. Binary like lazygit/tig/fzf stuff is not presented in the list

Then we might want to look at some other tool/methodologies :(. If we want to do a complete local installation and then transfer it over, it would take some more time to figure out an ideal strategy. One challenge is to figure out how to download and transfer plugins, LSPs, tools, etc. Tools could still be easy if they provide binaries for the other OS and we can just download and `scp` that. Let me put some more thought into it.


> I have a situation that I can’t access internet on remote machine(e.g. deploying software on a robot and can only access it through local networks), but my laptop/local machine could access internet. Then what’s best workflow for remote-nvim?

For now, you can setup a proxy server like [squid](http://www.squid-cache.org/) on remote and use that to connect to internet using remote SSH tunneling. You can follow this SO question for the steps: [Give server access to internet via client](https://unix.stackexchange.com/questions/116191/give-server-access-to-internet-via-client-connecting-by-ssh) and remote-neovim should work fine, as is.

**Comment by qlibp** [comment]
It's quite a work to prepare all the binaries for everyone, with so much different environments, I think the best way would be provide a common set of build tools, and we build the binary when we need it, just like treesitter, they build from source after we download it. If we go that further to provide all needed binary, it feels like we are implementing another package manager.

**Comment by konosubakonoakua** [comment]
Why not adapt VSCode's strategy，download everything in the client (our local PC), zip them then use scp to copy the archive file to the ssh host (remote PC), then unzip and run the remote server something.

**Comment by amitds1997** [comment]
> Why not adapt VSCode's strategy，download everything in the client (our local PC), zip them then use scp to copy the archive file to the ssh host (remote PC), then unzip and run the remote server something.

Agree. We would adopt this strategy for local installation of Neovim server. This discussion is a bit more extended and talks about a possible way to ship necessary binaries as well. For example, telescope fzf plugin requires `fzf` to be present on the path. Is there a simple and easy way to make that available on the remote host or not.

**Comment by qlibp** [comment]
> Why not adapt VSCode's strategy，download everything in the client (our local PC), zip them then use scp to copy the archive file to the ssh host (remote PC), then unzip and run the remote server something.

simply unzip the file won’t work, take a look at my problem. Even the lua lsp has some hard coded path generated during installation procedure.

**Comment by amitds1997** [comment]
> simply unzip the file won’t work, take a look at my problem. Even the lua lsp has some hard coded path generated during installation procedure.

Lua LSP should be easily manageable. I use it all the time in my remote development. If you want it to auto-install, use something like [mason.nvim](https://github.com/williamboman/mason.nvim) and auto install it using [mason-lspconfig](https://github.com/williamboman/mason-lspconfig.nvim).

**Comment by amitds1997** [comment]
We don't have a clear way forward for this right now. If anyone has any new ideas, please create a new issue. Thanks!
