### ISSUE TITLE
Get remote OS failed

### ISSUE THREAD

**Issue by guzman109** [amitds1997/remote-nvim.nvim#54]
**Describe the bug**
Last push fixed my other issue #52. But now I'm experiencing another one.

ERROR Thu 28 Sep 2023 12:35:19 PM EDT .local/share/nvim/lazy/remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:575: 'Get remote OS' failed.
stack traceback:
	.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:575: in function '_handle_job_completion'
	.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:593: in function 'run_command'
	.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:172: in function '_get_remote_os'
	.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:106: in function '_setup_workspace_variables'
	.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:519: in function <.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:518>
	[C]: in function 'pcall'
	.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:416: in function <.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:415>
ERROR Thu 28 Sep 2023 01:02:56 PM EDT .local/share/nvim/lazy/remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:418: /usr/share/nvim/runtime/lua/vim/ui.lua:50: E5560: vimL function must not be called in a lua loop callback

**To Reproduce**
Same as issue #52 

**System Info**
* Your local OS: Ubuntu 23.04
* Local Neovim version: 0.9.2
* Remote host OS (if applicable): Rocky
* Remote Neovim version (if applicable): None

**Additional context**

**Comment by amitds1997** [comment]
The stack trace corresponds to the v0.1.0 release instead of the release with the fix (v0.1.1). Can you re-check that you have the latest release? If possible, try re-installing it. Do let me know if you still see the issue.

**Comment by guzman109** [comment]
Nope that worked. I did receive a permission error though with scp. 

`scp: dest open "/home/<username>/.remote-nvim/workspaces/Dacax5Yjfy/.config/nvim/.git/objects/pack/pack-28d680298efeb402e4e59aab258e53485ae2e7bc.pack": Permission denied`

`scp: dest open "/home/<username>/.remote-nvim/workspaces/Dacax5Yjfy/.config/nvim/.git/objects/pack/pack-28d680298efeb402e4e59aab258e53485ae2e7bc.idx": Permission denied`

**Comment by amitds1997** [comment]
> Nope that worked. 
So, it worked or it didn't? 😅

> I did receive a permission error though with scp. 
> 
> `scp: dest open "/home/<username>/.remote-nvim/workspaces/Dacax5Yjfy/.config/nvim/.git/objects/pack/pack-28d680298efeb402e4e59aab258e53485ae2e7bc.pack": Permission denied`
> 
> `scp: dest open "/home/<username>/.remote-nvim/workspaces/Dacax5Yjfy/.config/nvim/.git/objects/pack/pack-28d680298efeb402e4e59aab258e53485ae2e7bc.idx": Permission denied`
> 

Hmm 🤔. I have seen this popup in some of my dev containers and is usually fixed by just hitting the update keymap again in lazy.nvim. Did you have to do something else?

**Comment by guzman109** [comment]
Yes it worked. Not sure what you mean by ignoring the folders?

**Comment by amitds1997** [comment]
> Yes it worked.

Awesome 👍🏼

> Not sure what you mean by ignoring the folders?

I meant something like ignoring the `.git` folder copy on remote, but then we want to keep things as transparent as possible so I guess we should not introduce such things.
