### ISSUE TITLE
Get stuck on the "Find free port on remote running" msg

### ISSUE THREAD

**Issue by lucaspeixotoac** [amitds1997/remote-nvim.nvim#55]
**Describe the bug**
"Find free port on remote running"

**To Reproduce**
1. Install the plugin
2. Setup a docker container at port 35222 (ssh)
3. Try to connect to the remote server
4. Get stuck on the "Find free port on remote running" msg

**Expected behavior**
Go forward in the setup process

**Screenshots**
![image](https://github.com/amitds1997/remote-nvim.nvim/assets/117937435/99649199-b65c-4009-b566-56df6e0d31f3)

**System Info**
* Your local OS: Ubuntu
* Local Neovim version: v0.8.3
* Remote host OS (if applicable): Ubuntu
* Remote Neovim version (if applicable): v0.8.3

**Comment by amitds1997** [comment]
Thanks for reporting this! Let me have a look. 

While I do that, if you could possibly do the following and share results, it would make my task quite easy.
1. Reproduce the issue using the [minimal init file](https://github.com/amitds1997/remote-nvim.nvim/blob/87dcd85942a5fbbc4e0a54aa4c3371e16f7a2e4c/tests/init.lua). Start your neovim instance with `nvim -u init.lua` (`init.lua` being the above file).
2. If you are able to reproduce the issue, share the output of the `:RemoteLog` command. This would give me more insight into what's happening behind the scenes.
3. The `init.lua` file creates a `.tests` directory where it stores all the configuration. Please delete it after you are done with your reproduction. Thanks!

**Comment by amitds1997** [comment]
Closing due to no response. Was unable to reproduce this.
