### ISSUE TITLE
the client always in TERMINAL mode, if input C-\ C-n, it will enter the local nvim thread context?

### ISSUE THREAD

**Issue by littenglt** [amitds1997/remote-nvim.nvim#84]
I noticed that after the client startup, it stay in TERMINAL mode. 
![image](https://github.com/amitds1997/remote-nvim.nvim/assets/146831861/19118a4b-a87f-4ad3-83ca-de8dfed3c0ca)

If I input C-\ C-n to exit terminal mode, it backs to the local nvim thread context which makes it is hard to used it
how to make the clent works like create an new nvim thread context
Can we open new terminal or window directly like remote-ssh's behavior on vscode

**Comment by amitds1997** [comment]
Yup, you can. You can define a custom callback in your configuration that would be called when launching the client. See [this example for inspiration](Yup, you can. You can define a custom callback in your configuration that would be called when launching the client. See). This is how I launch my code in a new tab on Wezterm. You can define your own callback similarly to launch it in a new tab or call any other command with that information. 

For more information about parameters passed to the callback, see Advanced configuration in the [installation](https://github.com/amitds1997/remote-nvim.nvim?tab=readme-ov-file#-installation) section of README.
The two parameters passed are

**Comment by amitds1997** [comment]
@littenglt Did this solve your problem? If yes, please feel free to close this issue. If not, let me know what you were expecting. 

Please note: the syntax for the callback has been altered slightly in the latest release. So, you would have to update your configuration once. I have updated the wiki accordingly and also added what to change in [this deprecation message](https://github.com/amitds1997/remote-nvim.nvim/discussions/78#discussioncomment-8472042).
