### ISSUE TITLE
Plugin connect to host but won't copy the .config file to the session dir

### ISSUE THREAD

**Issue by yosefyehoshua** [amitds1997/remote-nvim.nvim#90]
Hi, great work on the plugin, but i can't figure out how to connect to my host
I'm using LazyVim distro with the default remote-nvim.nvim settings:

```
return {
  "amitds1997/remote-nvim.nvim",
  tag = "v0.0.1",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "MunifTanjim/nui.nvim",
    "rcarriga/nvim-notify",
    "nvim-telescope/telescope.nvim",
  },
  config = true,
}
```

But the plugin is stuck on the message:  Running installation script... completed
and nothing happens. Looking at ~/.remote-nvim i get:

```
~$ tree -d .remote-nvim/workspaces/HUza2WYq5Q/
.remote-nvim/workspaces/HUza2WYq5Q/

0 directories
```
 
Meaning the session dir is empty.

Checking the RemoteLog I get:

`[ERROR Sat Mar  2 20:16:45 2024] ~/.local/share/LazyVim/lazy/remote-nvim.nvim/lua/remote-nvim/providers/ssh/ssh_provider.lua:630: "ssh -p 22 user_name@<host ip addr> 'chmod +x ~/.remote-nvim/scripts/neovim_install.sh && ~/.remote-nvim/scripts/neovim_install.sh -v v0.9.5 -d ~/.remote-nvim'" command failed to execute on remote host "user_name@<host ip addr>"
`

**Comment by amitds1997** [comment]
Hi, thanks for reporting in. As a first step, could you upgrade to the latest version. The tag is set to `0.0.1` which was the very first release. Since then several releases with improvements have been published.

**Comment by yosefyehoshua** [comment]
oh yeah foolish mistake, I can connect now thank! but I think that because my config is `.remote-nvim/workspaces/HUza2WYq5Q/.config/LazyVim` instead of `.remote-nvim/workspaces/HUza2WYq5Q/.config/nvim` is pops a clean nvim window and doesn't load the LazyVim config. Is there any way to set it so it will copy the LazyVim dir name as nvim?

**Comment by amitds1997** [comment]
Yes, you can.

```lua
{
   "amitds1997/remote-nvim.nvim",
   version = "*", -- Pin to GitHub releases
   dependencies = {
       "nvim-lua/plenary.nvim", -- For standard functions
       "MunifTanjim/nui.nvim", -- To build the plugin UI
       "nvim-telescope/telescope.nvim", -- For picking b/w different remote methods
   },
   config = {
     remote = {
       copy_dirs = {
         config = {
           base = vim.fn.stdpath("config"), -- Just update this base value to whatever path your configuration should be copied over from
         }
       }
     }
   }
}
```

You can read more about what all can be configured under **Advanced Configuration** in https://github.com/amitds1997/remote-nvim.nvim?tab=readme-ov-file#-installation

**Comment by yosefyehoshua** [comment]
Thanks, acually now i get the following error even when i use the default config:

`ERROR Sun Mar  3 18:13:42 2024 .local/share/LazyVim/lazy/remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:876: 'Testing remote connection' failed.
stack traceback:
	.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:877: in function '_handle_job_completion'
	.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:918: in function 'run_command'
	.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:131: in function '_setup_workspace_variables'
	.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:774: in function '_launch_neovim'
	.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:789: in function <.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:788>
	[C]: in function 'xpcall'
	.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:669: in function <.../remote-nvim.nvim/lua/remote-nvim/providers/provider.lua:668> 

FAILED JOB OUTPUT (SO FAR)
ssh: Could not resolve hostname <host addr>:22: nodename nor servname provided, or not known`

**Comment by amitds1997** [comment]
Somehow the hostname was not passed down to the SSH command. This should not happen. 

Could you share
1. What method are you using to connect to the remote? Is it a host in your SSH Config file or is it a password based authentication. If password based authentication, what is the command that you use. Replace sensitive parts as needed.
2. Your current plugin configuration

This would help me replicate things at my end and figure out the resolution.

**Comment by yosefyehoshua** [comment]
1. I'm using :RemoteStart <User name>@<host addr>:22. password based

2. 
```
return {
  "amitds1997/remote-nvim.nvim",
  version = "*", -- Pin to GitHub releases
  dependencies = {
    "nvim-lua/plenary.nvim", -- For standard functions
    "MunifTanjim/nui.nvim", -- To build the plugin UI
    "nvim-telescope/telescope.nvim", -- For picking b/w different remote methods
  },
  config = true,
}
```

**Comment by amitds1997** [comment]
Config seems alright.

> 1. I'm using `:RemoteStart <User name>@<host addr>:22` password based

1. Could you try running just `:RemoteStart` and re-connecting using the manual input method?
2. Was this saved configuration created from the previous release by any chance, before you upgraded to the latest release? I ask this because there are checks in place in the later releases to ensure that the hostname is never empty but somehow this configuration is empty.
3. Could you share the output of `~/.local/share/nvim/remote-nvim.nvim/workspace.json`. If you have done some configuratin at your end to move things around, it would be at the path which would be the output of `:lua= vim.fn.stdpath("data").."/remote-nvim.nvim/workspace.json"`. This would give a complete picture of what configuration has been stored for `<user name>@<host>:22` by the plugin.

**Comment by yosefyehoshua** [comment]
1. Did that it gave me the same error:
```
 Launch Neovim (Run no. 1) (no longer active)
   Testing remote connection
    Command: echo 'Hello'

    ssh: Could not resolve hostname <host addr>:22: nodename nor servname provided, or not known
```

2. I dont think so, becasue the connection was successful only after I updated the config as you told me. But after I tried to change the config as such, trouble started

> Yes, you can.
> 
> ```lua
> {
>    "amitds1997/remote-nvim.nvim",
>    version = "*", -- Pin to GitHub releases
>    dependencies = {
>        "nvim-lua/plenary.nvim", -- For standard functions
>        "MunifTanjim/nui.nvim", -- To build the plugin UI
>        "nvim-telescope/telescope.nvim", -- For picking b/w different remote methods
>    },
>    config = {
>      remote = {
>        copy_dirs = {
>          config = {
>            base = vim.fn.stdpath("config"), -- Just update this base value to whatever path your configuration should be copied over from
>          }
>        }
>      }
>    }
> }
> ```
> 
> What this would do is copy the local dir specified as `base` to `.config/nvim`. If this would not work for your use case for some reason, let me know. I have not worked with `LazyVim` so I am a bit ignorant about how your workflow currently loads its configuration.
> 
> You can read more about what all can be configured under **Advanced Configuration** in https://github.com/amitds1997/remote-nvim.nvim?tab=readme-ov-file#-installation

3.  `~/.local/share/LazyVim/remote-nvim.nvim/workspace.json ` is an empty array: `[]`

**Comment by amitds1997** [comment]
Hmm, so it is picking up the host name. Are you able to connect to the remote host from your terminal using `ssh <user-name>@<host>`? Because underneath the plugin, it calls the SSH command. The output seems eerily similar to what you would get if your machine is not able to connect to the remote host.

![image](https://github.com/amitds1997/remote-nvim.nvim/assets/29333147/ef775bce-d4a3-4afa-b779-33419edc1470)

**Comment by amitds1997** [comment]
Ah wait, I think I got it. I think you are providing the ssh input as `ssh <username>@<host>:22` which is incorrect syntax. If you want to specify a port, you have to use `-p` for it so it would be `ssh <username>@<host> -p 22` (but I would just chuck port 22 altogether since it's anyway the default port).

**Comment by yosefyehoshua** [comment]
yes I can :
``` <user>@mac-2 ~ % ssh <user name>@<host addr> -p 22 "echo hello"
hello
```

**Comment by yosefyehoshua** [comment]
If I'm trying to connect via ssh/.config file for the same host I get:

`  Launch Neovim (Run no. 1) (no longer active)
   Testing remote connection
   Determining OS on remote machine
   Choice: Choose remote OS (found OS 'Bytes per second: sent 21449.3, received 20289.9'): 
   Choice: Which Neovim version should be installed on remote?
   Determining remote user's home directory
   Creating custom neovim directories on remote
   Copying plugin scripts onto remote
    Command: COPY ~/.local/share/LazyVim/lazy/remote-nvim.nvim/scripts -> Bytes per second: sent 22679.7, received 21456.8/.remote-nvim

    21456.8/.remote-nvim: No such file or directory`

    
the ssh/.config :

HostName: <host addr>
LogLevel: verbose
Port: 22
User: <user>

**Comment by amitds1997** [comment]
> If I'm trying to connect via ssh/.config file of the same host I get:
> 
> ```
> 
>   Launch Neovim (Run no. 1) (no longer active)
>    Testing remote connection
>    Determining OS on remote machine
>    Choice: Choose remote OS (found OS 'Bytes per second: sent 21449.3, received 20289.9'): 
>    Choice: Which Neovim version should be installed on remote?
>    Determining remote user's home directory
>    Creating custom neovim directories on remote
>    Copying plugin scripts onto remote
>     Command: COPY ~/.local/share/LazyVim/lazy/remote-nvim.nvim/scripts -> Bytes per second: sent 22679.7, received 21456.8/.remote-nvim
> ```
> 
> ```
> 21456.8/.remote-nvim: No such file or directory
> ```
> 
> the ssh/.config :
> 
> ```
> HostName: <host addr>
> LogLevel: verbose
> Port: 22
> User: <user>
> ```
Could you try removing the `LogLevel: verbose` temporarily and re-try?

**Comment by yosefyehoshua** [comment]
I removed the verbose and got:

```
  Launch Neovim (Run no. 1) (no longer active)
   Testing remote connection
   Determining OS on remote machine
   Choice: Which Neovim version should be installed on remote?
   Determining remote user's home directory
   Creating custom neovim directories on remote
   Copying plugin scripts onto remote
   Installing Neovim (if required)
    Command: chmod +x /home/yyehoshua/.remote-nvim/scripts/neovim_download.sh && chmod +x /home/yyehoshua/.remote-nvim/scripts/neovim_install.sh && /home/yyehoshua/.remote-nvim/scripts/neovim_install.sh -v v0.9.5 -d /home/yyehoshua/.remote-nvim

    Neovim installation is corrupted. Would re-install...
    Downloading Neovim...
    curl: (28) Failed to connect to github.com port 443: Connection timed out
```

**Comment by yosefyehoshua** [comment]
I removed the verbose and got:

```
  Launch Neovim (Run no. 1) (no longer active)
   Testing remote connection
   Determining OS on remote machine
   Choice: Which Neovim version should be installed on remote?
   Determining remote user's home directory
   Creating custom neovim directories on remote
   Copying plugin scripts onto remote
   Installing Neovim (if required)
    Command: chmod +x /home/yyehoshua/.remote-nvim/scripts/neovim_download.sh && chmod +x ~/.remote-nvim/scripts/neovim_install.sh && ~/.remote-nvim/scripts/neovim_install.sh -v v0.9.5 -d ~/.remote-nvim

    Neovim installation is corrupted. Would re-install...
    Downloading Neovim...
    curl: (28) Failed to connect to github.com port 443: Connection timed out
```

**Comment by amitds1997** [comment]
Is your remote host perhaps in a region from where it is hard to connect to GitHub?

You should update your configuration to download Neovim locally and transfer it to the remote then:
```lua
config = {
 <your-original-config-values>,
  offline_mode = {
    enabled = true,
    no_github = false,
  },
}
```

Note that if you still face issues, you would have to go through [this](https://github.com/amitds1997/remote-nvim.nvim?tab=readme-ov-file#offline-on-remote-and-local-machine) and set up your configuration accordingly.

I am still not sure though what was blocking your original manual input run though :thinking: since both manual input and ssh config based connections use the same backend.

**Comment by yosefyehoshua** [comment]
ok I'll give it a try and see its solves it, I appreciate for your help!
