### ISSUE TITLE
Remote Connection ARM Support

### ISSUE THREAD

**Issue by ihersom** [amitds1997/remote-nvim.nvim#91]
When trying to connect to a remote machine like a raspberry pi, neovim app image installation fails due to it being an ARM platform

**Comment by amitds1997** [comment]
Hey, the Neovim project currently does not publishes releases for ARM arch :(

See https://github.com/neovim/neovim/issues/15143

Couple of possible solutions are:
1. Build from source
2. If you have neovim installed on remote system, just use that
3. Wait for someone to build those releases

If you are interested in 1 or 2, let me know and I will set this issue to also track their progress (they are close to completion).

**Comment by ihersom** [comment]
Ah I see! Thanks for the info. Your suggestions 1 and 2 sound like great options until neovim provides an official ARM build.
Thanks for your work on this plugin, very useful!

**Comment by aw1875** [comment]
@amitds1997 Just came back to your repo to see the progress and saw this issue. Not sure if you remember but I made [a similar note](https://github.com/amitds1997/remote-nvim.nvim/discussions/44#discussioncomment-6958038) a while back that I encountered on my project. Not sure if you'd be interested in implementing/having a PR done for this but for the project I referenced I just have a confirmation popup about building from source for any arm64 architecture, and then I handle the appropriate response.

**Comment by amitds1997** [comment]
Just to get back on this, there is ARM support in the [nightly releases](https://github.com/neovim/neovim/releases/tag/nightly) now :tada: 

Working on a new release with support for ARM.

**Comment by amitds1997** [comment]
Hey all, I merged support for either building from source or using Neovim already installed on the remote as an alternative in the latest release: [v0.3.0](https://github.com/amitds1997/remote-nvim.nvim/releases/tag/v0.3.0). Going ahead and closing this one for now. Will create a fresh PR to handle ARM-binary release as and when they become available upstream.
